name: Julia CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1: Run Unit Tests
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.1'

      - name: Install dependencies
        run: |
          julia --project=@. -e 'using Pkg; Pkg.instantiate()'

      - name: Run tests
        run: |
          julia --project=@. -e 'using Pkg; Pkg.test()'

  # Job 2: Check Code Formatting
  format:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.1'

      - name: Install JuliaFormatter
        run: |
          julia --project=@. -e 'using Pkg; Pkg.add("JuliaFormatter")'

      - name: Run JuliaFormatter
        run: |
          julia --project=@. -e 'using JuliaFormatter; format(".", verbose=true)'

      - name: Verify Formatting
        run: |
          git diff --exit-code || (echo "Code is not formatted. Run JuliaFormatter locally." && exit 1)

  # Job 3: Static Analysis with JET
  static-analysis:
    name: Static Analysis with JET
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.1'

      - name: Install JET
        run: |
          julia --project=@. -e 'using Pkg; Pkg.add("JET")'

      - name: Run JET Analysis
        run: |
          julia --project=@. -e 'using JET; report_package()'
