name: format check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.2'

      - name: Install JuliaFormatter
        run: |
          julia -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="1.0.62"))'

      - name: Run JuliaFormatter
        run: |
          julia --project=@. -e 'using JuliaFormatter; format(".", verbose=true, style=BlueStyle(), overwrite=false)'

      - name: Verify Formatting
        run: |
          git diff --exit-code || (echo "Code is not formatted. Run JuliaFormatter locally." && exit 1)
