name: Julia Format Check

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11.1'

      - name: Run JuliaFormatter
        run: |
          julia -e 'using JuliaFormatter; format(".", verbose=true)'

      - name: Verify Formatting
        run: |
          git diff --exit-code || (echo "Code is not formatted. Run JuliaFormatter locally." && exit 1)

